# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections:
  category:
    output: true
      
# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
plugins:
  - jekyll-paginate

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
url:     https://keuperict.nl
repository: "jkeuper/jkeuper.github.io"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"

# Outputting
permalink:     /posts/:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: /page:num
timezone:      null

quiet:    false
defaults:
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      comments: false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  wrap:              div
  line_numbers:      inline
  line_number_start: 1
  tab_width:         4
  bold_every:        10
  css:               style


include: ['_pages']
